from django.db import models

# Create your models here.
"""User: (ID(generated by default)(PK), name, email, password)
Movie: (ID(generated by default)(PK), name, releasedDate, production, duration, plot, image, rating)
Review: (ID(generated by default)(PK), uid(FK), mid(FK), reviewText, rating, dateTime)"""

class User(models.Model):
    ID=models.IntegerField(auto_created=True,primary_key=True)
    name=models.CharField(max_length=30)
    email=models.CharField(max_length=254)
    password=models.CharField(max_length=128)
    
class Movie(models.Model):
    ID=models.IntegerField(auto_created=True,primary_key=True)
    name=models.CharField(max_length=30)
    releasedDate=models.DateField()
    production=models.CharField(max_length=30)
    duration=models.TimeField()
    plot=models.TextField()
    image=models.ImageField(upload_to="images")
    rating=models.FloatField()

class Review(models.Model):
    ID=models.IntegerField(auto_created=True,primary_key=True)
    uid=models.ForeignKey(User,on_delete=models.CASCADE)
    mid=models.ForeignKey(Movie,on_delete=models.CASCADE)
    reviewText=models.TextField()
    rating=models.FloatField()
    dateTime=models.DateTimeField()