# Generated by Django 3.0.2 on 2021-02-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('releasedDate', models.DateField()),
                ('production', models.CharField(max_length=30)),
                ('duration', models.TimeField()),
                ('plot', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('reviewText', models.TextField()),
                ('rating', models.FloatField()),
                ('dateTime', models.DateTimeField()),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registerapp.Movie')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registerapp.User')),
            ],
        ),
    ]
