# Generated by Django 3.0.2 on 2021-03-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
